/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author arni
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        ImageIcon imagenLogo = new ImageIcon(getClass().getResource("/images/logo3.png"));
        Icon icon1 = new ImageIcon(imagenLogo.getImage().getScaledInstance(imgLogo.getWidth(), imgLogo.getHeight(), Image.SCALE_DEFAULT));
        imgLogo.setIcon(icon1);
        
        ImageIcon imagenBus = new ImageIcon(getClass().getResource("/images/bus.png"));
        Icon icon2 = new ImageIcon(imagenBus.getImage().getScaledInstance(imgBus.getWidth(), imgBus.getHeight(), Image.SCALE_DEFAULT));
        imgBus.setIcon(icon2);
        
        ImageIcon imagenCamioneta = new ImageIcon(getClass().getResource("/images/camioneta.png"));
        Icon icon3 = new ImageIcon(imagenCamioneta.getImage().getScaledInstance(imgCamioneta.getWidth(), imgCamioneta.getHeight(), Image.SCALE_DEFAULT));
        imgCamioneta.setIcon(icon3);
        
        ImageIcon imagenMoto = new ImageIcon(getClass().getResource("/images/motocicleta.png"));
        Icon icon4 = new ImageIcon(imagenMoto.getImage().getScaledInstance(imgMoto.getWidth(), imgMoto.getHeight(), Image.SCALE_DEFAULT));
        imgMoto.setIcon(icon4);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        imgMoto = new javax.swing.JLabel();
        imgBus = new javax.swing.JLabel();
        imgCamioneta = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 30));

        imgMoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMotoMouseClicked(evt);
            }
        });
        jPanel1.add(imgMoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 130, 140));

        imgBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgBus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBusMouseClicked(evt);
            }
        });
        jPanel1.add(imgBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, 140));

        imgCamioneta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgCamioneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCamionetaMouseClicked(evt);
            }
        });
        jPanel1.add(imgCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 130, 140));

        btnSalir.setBackground(new java.awt.Color(255, 55, 55));
        btnSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 80, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 58, 64));
        jLabel1.setText("Bus");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 58, 64));
        jLabel2.setText("Camioneta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 58, 64));
        jLabel3.setText("Motocicleta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        labelBienvenida.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelBienvenida.setForeground(new java.awt.Color(52, 58, 64));
        labelBienvenida.setText("BIENVENIDO");
        jPanel1.add(labelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void imgBusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBusMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        BusFrame busF = new BusFrame();
        busF.labelUserActive.setText(labelBienvenida.getText());
        busF.setVisible(true);
    }//GEN-LAST:event_imgBusMouseClicked

    private void imgCamionetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCamionetaMouseClicked
        this.setVisible(false);
        CamionetaFrame camionetaF = new CamionetaFrame();
        camionetaF.labelUserActive.setText(labelBienvenida.getText());
        camionetaF.setVisible(true);

    }//GEN-LAST:event_imgCamionetaMouseClicked

    private void imgMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMotoMouseClicked
        this.setVisible(false);
        MotoFrame motoF = new MotoFrame();
        motoF.labelUserActive.setText(labelBienvenida.getText());
        motoF.setVisible(true);
        
    }//GEN-LAST:event_imgMotoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgBus;
    private javax.swing.JLabel imgCamioneta;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgMoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel labelBienvenida;
    // End of variables declaration//GEN-END:variables
}
