/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author arni
 */
public class Login extends javax.swing.JFrame {
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        ImageIcon imagenLogo = new ImageIcon(getClass().getResource("/images/logo3.png"));
        Icon icon1 = new ImageIcon(imagenLogo.getImage().getScaledInstance(imgLogo.getWidth(), imgLogo.getHeight(), Image.SCALE_DEFAULT));
        imgLogo.setIcon(icon1);
        
        ImageIcon imagenLogin = new ImageIcon(getClass().getResource("/images/imgLogin.png"));
        Icon icon2 = new ImageIcon(imagenLogin.getImage().getScaledInstance(imgLogin.getWidth(), imgLogin.getHeight(), Image.SCALE_DEFAULT));
        imgLogin.setIcon(icon2);
        
        ImageIcon imagenUser = new ImageIcon(getClass().getResource("/images/user.png"));
        Icon icon3 = new ImageIcon(imagenUser.getImage().getScaledInstance(imgUser.getWidth(), imgUser.getHeight(), Image.SCALE_DEFAULT));
        imgUser.setIcon(icon3);
        
        ImageIcon imagenPassword = new ImageIcon(getClass().getResource("/images/lock.png"));
        Icon icon4 = new ImageIcon(imagenPassword.getImage().getScaledInstance(imgPassword.getWidth(), imgPassword.getHeight(), Image.SCALE_DEFAULT));
        imgPassword.setIcon(icon4);
        
        inputEmail1.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
        inputPassword.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        imgLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        inputEmail1 = new javax.swing.JTextField();
        imgPassword = new javax.swing.JLabel();
        imgUser = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        labelAlertUser = new javax.swing.JLabel();
        labelAlertPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 55, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 30));
        jPanel1.add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 350, 250));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 55, 55));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        labelPassword.setForeground(new java.awt.Color(52, 58, 64));
        labelPassword.setText("Password*");
        jPanel1.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        labelEmail.setForeground(new java.awt.Color(52, 58, 64));
        labelEmail.setText("User*");
        jPanel1.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        inputEmail1.setBackground(new java.awt.Color(240, 240, 240));
        inputEmail1.setBorder(null);
        jPanel1.add(inputEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 250, 40));
        jPanel1.add(imgPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 20, 20));
        jPanel1.add(imgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 20, 20));

        inputPassword.setBackground(new java.awt.Color(240, 240, 240));
        inputPassword.setBorder(null);
        jPanel1.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 250, 40));

        btnLogin.setBackground(new java.awt.Color(255, 55, 55));
        btnLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 250, 40));

        btnSalir.setBackground(new java.awt.Color(255, 55, 55));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 70, 30));

        labelAlertUser.setForeground(new java.awt.Color(255, 55, 55));
        jPanel1.add(labelAlertUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        labelAlertPassword.setForeground(new java.awt.Color(255, 55, 55));
        jPanel1.add(labelAlertPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        
        
        
        String user = inputEmail1.getText();
        char pass[] = inputPassword.getPassword();
        String pwd = new String(pass);

        
            System.out.println("User: "+user);
            System.out.println("Pass: "+pwd);
        
            if(inputEmail1.getText().trim().isEmpty() && pwd.trim().isEmpty()){
                labelAlertUser.setText("User es un campo obligatorio");
                labelAlertPassword.setText("Password es un campo obligatorio");
                return;
            }else if(inputEmail1.getText().trim().isEmpty()){
                labelAlertUser.setText("User es un campo obligatorio");
            }else if(pwd.trim().isEmpty()){
                labelAlertPassword.setText("Password es un campo obligatorio");
            }else{
                this.setVisible(false);
                Home home = new Home();
                home.labelBienvenida.setText("Bienvenid@ "+user);        
                home.setVisible(true);
            }
            
               
            
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgPassword;
    private javax.swing.JLabel imgUser;
    private javax.swing.JTextField inputEmail1;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlertPassword;
    private javax.swing.JLabel labelAlertUser;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelPassword;
    // End of variables declaration//GEN-END:variables
}
