/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import clases.Moto;
import com.db4o.Db4oEmbedded;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author arni
 */
public class MotoFrame extends javax.swing.JFrame {

    public static ObjectContainer db = Db4oEmbedded.openFile("motocicleta.db4o");
    
    /**
     * Creates new form Bus
     */
    public MotoFrame() {
        initComponents();
        
          ImageIcon imagenLogo = new ImageIcon(getClass().getResource("/images/logo3.png"));
        Icon icon1 = new ImageIcon(imagenLogo.getImage().getScaledInstance(imgLogo.getWidth(), imgLogo.getHeight(), Image.SCALE_DEFAULT));
        imgLogo.setIcon(icon1);
        
        generarTabla();
        
    }
    
    public void limpiar(){
        inputPlaca.setText("");
        inputChasis.setText("");
        inputMarca.setText("");
        inputColor.setText("");
        inputCilindrada.setText("");
        inputCombustible.setSelectedIndex(0);
        inputModelo.setText("");
        groupBaulera.clearSelection();
        
    }
    /*
    public boolean validar(){
        String placa = inputPlaca.getText();
        String chasis = inputChasis.getText();
        String cilindrada = inputCilindrada.getText();
        String modelo = inputModelo.getText();
        String color = inputColor.getText();
        String marca = inputMarca.getText();
        int combustible = inputCombustible.getSelectedIndex();
        Boolean aireAcondicionadoSi = radioSiAire.isSelected();
        Boolean aireAcondicionadoNo = radioNoAire.isSelected();
    
         boolean botonAdicionar = (placa != "" && chasis != "" && cilindrada != "" && modelo != "" && color != "" && marca != "" && combustible ==0 && nroPuertas != "")?true:false;
             
         return botonAdicionar;
    }
    */
    public void generarTabla() {
        String columnas[] = {"Placa", "Chasis", "Marca", "Color", "Cilindrada", "combustible", "Modelo", "Baulera"};

        List<Moto> motos = db.query(Moto.class);

        String datos[][] = new String[motos.size()][8];

        for (int i = 0; i < motos.size(); i++) {
            datos[i][0] = motos.get(i).getPlaca();
            datos[i][1] = motos.get(i).getChasis();
            datos[i][2] = motos.get(i).getMarca();
            datos[i][3] = motos.get(i).getColor();
            datos[i][4] = motos.get(i).getCilindrada() + "";
            datos[i][5] = motos.get(i).getCombustible();
            datos[i][6] = motos.get(i).getModelo() + "";
            
            datos[i][7] = (motos.get(i).isBaulera())?"Si":"No";
        }

        tablaAutos.setModel(new javax.swing.table.DefaultTableModel(datos, columnas));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupBaulera = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputColor = new javax.swing.JTextField();
        inputCilindrada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputChasis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputModelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputMarca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAutos = new javax.swing.JTable();
        inputCombustible = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        labelAlertPlaca = new javax.swing.JLabel();
        labelAlertCilindrada = new javax.swing.JLabel();
        labelAlertColor = new javax.swing.JLabel();
        labelAlertCombustible = new javax.swing.JLabel();
        labelAlertChasis = new javax.swing.JLabel();
        labelAlertModelo = new javax.swing.JLabel();
        labelAlertMarca = new javax.swing.JLabel();
        labelAlertBaulera = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        labelUserActive = new javax.swing.JLabel();
        radioBauleraSi = new javax.swing.JRadioButton();
        radioBauleraNo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 58, 64));
        jLabel1.setText("MOTOCICLETA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(52, 58, 64));
        jLabel2.setText("Placa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(52, 58, 64));
        jLabel3.setText("Cilindrada");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        inputColor.setBackground(new java.awt.Color(240, 240, 240));
        inputColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        inputColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputColorActionPerformed(evt);
            }
        });
        inputColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputColorKeyReleased(evt);
            }
        });
        jPanel1.add(inputColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 110, 30));

        inputCilindrada.setBackground(new java.awt.Color(240, 240, 240));
        inputCilindrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        inputCilindrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCilindradaActionPerformed(evt);
            }
        });
        inputCilindrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputCilindradaKeyReleased(evt);
            }
        });
        jPanel1.add(inputCilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 110, 30));

        jLabel7.setForeground(new java.awt.Color(52, 58, 64));
        jLabel7.setText("Combustible");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jLabel5.setForeground(new java.awt.Color(52, 58, 64));
        jLabel5.setText("Color");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        inputPlaca.setBackground(new java.awt.Color(240, 240, 240));
        inputPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        inputPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputPlacaKeyReleased(evt);
            }
        });
        jPanel1.add(inputPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 30));

        jLabel4.setForeground(new java.awt.Color(52, 58, 64));
        jLabel4.setText("Chasis");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        inputChasis.setBackground(new java.awt.Color(240, 240, 240));
        inputChasis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        inputChasis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputChasisKeyReleased(evt);
            }
        });
        jPanel1.add(inputChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 120, 30));

        jLabel6.setForeground(new java.awt.Color(52, 58, 64));
        jLabel6.setText("Modelo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        inputModelo.setBackground(new java.awt.Color(240, 240, 240));
        inputModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        inputModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputModeloActionPerformed(evt);
            }
        });
        inputModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputModeloKeyReleased(evt);
            }
        });
        jPanel1.add(inputModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 110, 30));

        jLabel8.setForeground(new java.awt.Color(52, 58, 64));
        jLabel8.setText("Marca");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        inputMarca.setBackground(new java.awt.Color(240, 240, 240));
        inputMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        inputMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMarcaActionPerformed(evt);
            }
        });
        inputMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputMarcaKeyReleased(evt);
            }
        });
        jPanel1.add(inputMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 110, 30));

        jLabel9.setForeground(new java.awt.Color(52, 58, 64));
        jLabel9.setText("Baulera");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        btnAdicionar.setBackground(new java.awt.Color(40, 167, 69));
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorder(null);
        btnAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseClicked(evt);
            }
        });
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 90, 30));

        btnModificar.setBackground(new java.awt.Color(108, 117, 125));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 80, 30));

        btnSeleccionar.setBackground(new java.awt.Color(255, 193, 7));
        btnSeleccionar.setForeground(new java.awt.Color(52, 58, 64));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setBorder(null);
        btnSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(220, 53, 69));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 80, 30));

        tablaAutos.setBackground(new java.awt.Color(240, 240, 240));
        tablaAutos.setForeground(new java.awt.Color(52, 58, 64));
        tablaAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAutos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 790, 150));

        inputCombustible.setBackground(new java.awt.Color(240, 240, 240));
        inputCombustible.setForeground(new java.awt.Color(52, 58, 64));
        inputCombustible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Gasolina 95 octanos", "Gasolina 98 octanos" }));
        inputCombustible.setToolTipText("");
        inputCombustible.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inputCombustibleItemStateChanged(evt);
            }
        });
        jPanel1.add(inputCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 140, -1));

        btnSalir.setBackground(new java.awt.Color(255, 55, 55));
        btnSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 80, 40));

        jButton1.setBackground(new java.awt.Color(0, 123, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 110, 40));

        btnLimpiar.setBackground(new java.awt.Color(13, 202, 240));
        btnLimpiar.setForeground(new java.awt.Color(52, 58, 64));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 90, 30));

        labelAlertPlaca.setFont(new java.awt.Font("Garuda", 1, 10)); // NOI18N
        labelAlertPlaca.setForeground(new java.awt.Color(220, 53, 69));
        jPanel1.add(labelAlertPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        labelAlertCilindrada.setFont(new java.awt.Font("Garuda", 1, 10)); // NOI18N
        labelAlertCilindrada.setForeground(new java.awt.Color(220, 53, 69));
        jPanel1.add(labelAlertCilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        labelAlertColor.setFont(new java.awt.Font("Garuda", 1, 10)); // NOI18N
        labelAlertColor.setForeground(new java.awt.Color(220, 53, 69));
        jPanel1.add(labelAlertColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        labelAlertCombustible.setFont(new java.awt.Font("Garuda", 1, 10)); // NOI18N
        labelAlertCombustible.setForeground(new java.awt.Color(220, 53, 69));
        jPanel1.add(labelAlertCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, -1, -1));

        labelAlertChasis.setFont(new java.awt.Font("Garuda", 1, 10)); // NOI18N
        labelAlertChasis.setForeground(new java.awt.Color(220, 53, 69));
        jPanel1.add(labelAlertChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        labelAlertModelo.setFont(new java.awt.Font("Garuda", 1, 10)); // NOI18N
        labelAlertModelo.setForeground(new java.awt.Color(220, 53, 69));
        jPanel1.add(labelAlertModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        labelAlertMarca.setFont(new java.awt.Font("Garuda", 1, 10)); // NOI18N
        labelAlertMarca.setForeground(new java.awt.Color(220, 53, 69));
        jPanel1.add(labelAlertMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        labelAlertBaulera.setFont(new java.awt.Font("Garuda", 1, 10)); // NOI18N
        labelAlertBaulera.setForeground(new java.awt.Color(220, 53, 69));
        jPanel1.add(labelAlertBaulera, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));
        jPanel1.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));
        jPanel1.add(labelUserActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        radioBauleraSi.setBackground(new java.awt.Color(240, 240, 240));
        groupBaulera.add(radioBauleraSi);
        radioBauleraSi.setForeground(new java.awt.Color(52, 58, 64));
        radioBauleraSi.setText("Si");
        radioBauleraSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBauleraSiActionPerformed(evt);
            }
        });
        jPanel1.add(radioBauleraSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        radioBauleraNo.setBackground(new java.awt.Color(240, 240, 240));
        groupBaulera.add(radioBauleraNo);
        radioBauleraNo.setForeground(new java.awt.Color(52, 58, 64));
        radioBauleraNo.setText("No");
        radioBauleraNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBauleraNoActionPerformed(evt);
            }
        });
        jPanel1.add(radioBauleraNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputColorActionPerformed

    private void inputCilindradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCilindradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCilindradaActionPerformed

    private void inputModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputModeloActionPerformed

    private void inputMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMarcaActionPerformed

    private void btnAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseClicked
        //String columnas[] = {"Placa", "Chasis", "Marca","Color","Cilindrada","combustible", "Modelo", "Aire acondicionado"};

        try {
            if(inputPlaca.getText().trim().isEmpty() && inputCilindrada.getText().trim().isEmpty() && 
                    inputColor.getText().trim().isEmpty() && inputCombustible.getSelectedIndex()==0 &&
                    inputChasis.getText().trim().isEmpty() && inputModelo.getText().trim().isEmpty() &&
                    inputMarca.getText().trim().isEmpty() && !radioBauleraSi.isSelected() && !radioBauleraNo.isSelected()){
                labelAlertCilindrada.setText("Cilindrada es obligatorio");
                labelAlertColor.setText("Color es obligatorio");
                labelAlertCombustible.setText("Combustible es obligatorio");
                labelAlertPlaca.setText("Placa es obligatorio");
                
                labelAlertChasis.setText("Chasis es obligatorio");
                labelAlertModelo.setText("Modelo es obligatorio");
                labelAlertMarca.setText("Marca es obligatorio");
                labelAlertBaulera.setText("Baulera es obligatorio");
                
                
            }else if(inputCilindrada.getText().trim().isEmpty()){
                labelAlertCilindrada.setText("Cilindrada es obligatorio");
            }
            
            else if(inputPlaca.getText().trim().isEmpty() ){
               labelAlertPlaca.setText("Placa es obligatorio"); 
            }
            
            else if(inputColor.getText().trim().isEmpty()){
                labelAlertColor.setText("Color es obligatorio");
            }
            
            else if(inputCombustible.getSelectedIndex() == 0){
               labelAlertCombustible.setText("Combustible es obligatorio"); 
            }
            
            else if(inputChasis.getText().trim().isEmpty()){
                labelAlertChasis.setText("Chasis es obligatorio");
            }
            
            else if(inputModelo.getText().trim().isEmpty() ){
               labelAlertModelo.setText("Modelo es obligatorio"); 
            }
            
            else if(inputMarca.getText().trim().isEmpty()){
                labelAlertMarca.setText("Marca es obligatorio");
            }
            
            else if(!radioBauleraSi.isSelected() && !radioBauleraNo.isSelected()){
               labelAlertBaulera.setText("Este campo es obligatorio"); 
            }
            else{
                String placa = inputPlaca.getText();
                String chasis = inputChasis.getText();
                String cilindrada = inputCilindrada.getText();
                String modelo = inputModelo.getText();
                String color = inputColor.getText();
                String marca = inputMarca.getText();
                String combustible = inputCombustible.getSelectedItem().toString();
                Boolean baulera = (radioBauleraSi.isSelected()?true:false);

                Moto moto = new Moto();
                moto.setPlaca(placa);
                moto.setChasis(chasis);
                moto.setCilindrada(Integer.parseInt(cilindrada));
                moto.setModelo(Integer.parseInt(modelo));
                moto.setColor(color);
                moto.setMarca(marca);
                moto.setCombustible(combustible);
                moto.setBaulera(radioBauleraSi.isSelected()?true:false);

                db.store(moto);
                generarTabla();
                limpiar();
            }
            
        } catch (Exception e) {
            System.out.println("Algo paso");
            System.out.println(e);
        }
    
    }//GEN-LAST:event_btnAdicionarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked

    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        String placa = inputPlaca.getText();
        String chasis = inputChasis.getText();
        String cilindrada = inputCilindrada.getText();
        String modelo = inputModelo.getText();
        String color = inputColor.getText();
        String marca = inputMarca.getText();
        String combustible = inputCombustible.getSelectedItem().toString();
        Boolean baulera = radioBauleraSi.isSelected()?true:false;

        //        Auto autoModificado = new Auto(marca, chasis, Integer.parseInt(modelo), color, combustible, 0,Integer.parseInt(cilindrada),placa, Boolean.parseBoolean(aireAcondicionado));
        /*Auto autoModificado = new Auto(placa);*/

        Moto motoModificado = new Moto();
        motoModificado.setPlaca(placa);
        /*
        autoModificado.setChasis(chasis);
        autoModificado.setCilindrada(Integer.parseInt(cilindrada));
        autoModificado.setModelo(Integer.parseInt(modelo));
        autoModificado.setColor(color);
        autoModificado.setMarca(marca);
        autoModificado.setCombustible(combustible);
        autoModificado.setAireAcondicionado(Boolean.parseBoolean(aireAcondicionado));
        */
        ObjectSet informacion = db.queryByExample(motoModificado);
        //listResult(informacion);
        
        Moto motoEncontrado = (Moto) informacion.next();

        motoEncontrado.setPlaca(placa);
        motoEncontrado.setChasis(chasis);
        motoEncontrado.setCilindrada(Integer.parseInt(cilindrada));
        motoEncontrado.setModelo(Integer.parseInt(modelo));
        motoEncontrado.setColor(color);
        motoEncontrado.setMarca(marca);
        motoEncontrado.setCombustible(combustible);
        motoEncontrado.setBaulera(baulera);

        db.store(motoEncontrado);
        generarTabla();
        btnAdicionar.setEnabled(true);
        
        limpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseClicked
        //         String columnas[] = {"Placa", "Chasis", "Marca","Color","Cilindrada","combustible", "Modelo", "Aire acondicionado"};
        int fila = tablaAutos.getSelectedRow();
        inputPlaca.setText(tablaAutos.getValueAt(fila, 0).toString());
        inputChasis.setText(tablaAutos.getValueAt(fila, 1).toString());

        inputMarca.setText(tablaAutos.getValueAt(fila, 2).toString());

        inputColor.setText(tablaAutos.getValueAt(fila, 3).toString());
        inputCilindrada.setText(tablaAutos.getValueAt(fila, 4).toString());
        inputCombustible.setSelectedItem(tablaAutos.getValueAt(fila, 5).toString());
        inputModelo.setText(tablaAutos.getValueAt(fila, 6).toString());

        radioBauleraSi.setSelected(tablaAutos.getValueAt(fila, 7).toString()=="Si"?true:false);
        radioBauleraNo.setSelected(tablaAutos.getValueAt(fila, 7).toString()=="No"?true:false);

        btnAdicionar.setEnabled(false);
    }//GEN-LAST:event_btnSeleccionarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked

        String placa = inputPlaca.getText();
        
        Moto motoModificado = new Moto();
        motoModificado.setPlaca(placa);

        ObjectSet informacion = db.queryByExample(motoModificado);

        Moto motoEncontrado = (Moto) informacion.next();

        db.delete(motoEncontrado);
        generarTabla();
        btnAdicionar.setEnabled(true);
        
        limpiar();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);  
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void inputPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPlacaKeyReleased
        // TODO add your handling code here:
        labelAlertPlaca.setText("");
    }//GEN-LAST:event_inputPlacaKeyReleased

    private void inputCilindradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCilindradaKeyReleased
        // TODO add your handling code here:
        labelAlertCilindrada.setText("");
    }//GEN-LAST:event_inputCilindradaKeyReleased

    private void inputColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputColorKeyReleased
        // TODO add your handling code here:
        labelAlertColor.setText("");
    }//GEN-LAST:event_inputColorKeyReleased

    private void inputCombustibleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inputCombustibleItemStateChanged
        // TODO add your handling code here:
        labelAlertCombustible.setText("");
    }//GEN-LAST:event_inputCombustibleItemStateChanged

    private void inputChasisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputChasisKeyReleased
        // TODO add your handling code here:
        labelAlertChasis.setText("");
    }//GEN-LAST:event_inputChasisKeyReleased

    private void inputModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputModeloKeyReleased
        // TODO add your handling code here:
        labelAlertModelo.setText("");
    }//GEN-LAST:event_inputModeloKeyReleased

    private void inputMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMarcaKeyReleased
        labelAlertMarca.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMarcaKeyReleased

    private void radioBauleraNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBauleraNoActionPerformed
    labelAlertBaulera.setText("");        
// TODO add your handling code here:
    }//GEN-LAST:event_radioBauleraNoActionPerformed

    private void radioBauleraSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBauleraSiActionPerformed
        labelAlertBaulera.setText("");
    }//GEN-LAST:event_radioBauleraSiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotoFrame().setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.ButtonGroup groupBaulera;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JTextField inputChasis;
    private javax.swing.JTextField inputCilindrada;
    private javax.swing.JTextField inputColor;
    private javax.swing.JComboBox<String> inputCombustible;
    private javax.swing.JTextField inputMarca;
    private javax.swing.JTextField inputModelo;
    private javax.swing.JTextField inputPlaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlertBaulera;
    private javax.swing.JLabel labelAlertChasis;
    private javax.swing.JLabel labelAlertCilindrada;
    private javax.swing.JLabel labelAlertColor;
    private javax.swing.JLabel labelAlertCombustible;
    private javax.swing.JLabel labelAlertMarca;
    private javax.swing.JLabel labelAlertModelo;
    private javax.swing.JLabel labelAlertPlaca;
    public static javax.swing.JLabel labelUserActive;
    private javax.swing.JRadioButton radioBauleraNo;
    private javax.swing.JRadioButton radioBauleraSi;
    private javax.swing.JTable tablaAutos;
    // End of variables declaration//GEN-END:variables
}
